### ISSUE TITLE
Social / Collaboration Skills Section?

### ISSUE THREAD

**Issue by wasciutto** [samoylenko/appseclearning#21]
Application security is career path with a heavy focus on "soft skills" due to the highly integrated nature of the role. For this I am thinking of topics such as: how to handle tough conversations, how to take feedback well, how to give feedback well, how to deal with difficult individuals, the "client" aspect of dealing with outside team members, general social networking, etc.

The role also feels especially dependent on a smooth functioning team, meaning that a professional in this field should have a good understanding of what a team with solid communication and teamwork should look like and how to maintain this.

There are a myriad of books and articles on these topics of course, and it would be especially helpful if someone who has already sifted through this category of material could provide recommendations. Many of these topics may or may not already be included in books on the topic of Dev Ops or project management.

**Comment by samoylenko** [comment]
I believe this is beyond this project. And the topic is too large, as you already said. I will be happy to see a merge request if you want to try (hence, assigned this to you), but suggest to address this separately

In short: this is a leadership topic, while this project is to help for beginners start their career. For the reasons described in this issue, CISSP book is listed 1st at the list of recommended books
