### ISSUE TITLE
Add agile stuff

### ISSUE THREAD

**Issue by samoylenko** [samoylenko/appseclearning#3]
Notes:

Agile?  
Boards?  
Scrum vs Kanban?

**Comment by wasciutto** [comment]
Yup, would be very useful to see input on this (yet another topic that is intimidating to approach as a newer professional). Would love to see, specifically, the implications of an "Agile" security team. Are we running agile internally, or just trying to be aware of the agile processes used by software development?

**Comment by samoylenko** [comment]
It's a much bigger topic than just this. Agile is much more than that. Unless there is a quick learning link, I don't think it's a subject for this document as well

**Comment by samoylenko** [comment]
But I guess there is a quick answer in scope of this project: we can recommend security professional to be agile. the rest will be implied. Now, both of us, reading 'The Goal' and 'The Phoenix Project' =)

**Comment by samoylenko** [comment]
@wasciutto I suggest to address the entire Agile section by just recommending a book - PR #24 , the "Agile application Security" book gives a very good intro in this. I don't think we can even try start describing this topic in our writing - it's way too large topic, and too many papers exist already
